### ISSUE TITLE
Error: The process '/usr/bin/git' failed with exit code 1

### ISSUE THREAD

**Issue by MinuraPunchihewa** [code-specialist/pypi-poetry-publish#7]
Hey guys,

First off, thank you so much for this great product you've created. It's going to make publishing packages to PyPI with Poetry so much easier!

I am running into the above error with the following workflow:
```
name: Build and publish python package

on:
  release:
    types: [published]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1.2
        with:
          BRANCH: "main"
          PACKAGE_DIRECTORY: "./my_package/"
          PYTHON_VERSION: "3.10"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
```

Do you guys have any idea what this could be? I faced the same issue with v1.

Here is the complete stack trace:
```
Run code-specialist/pypi-poetry-publish@v1
Run actions/checkout@v3
Syncing repository: MinuraPunchihewa/create-reactpy-app
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/33f23337-2f00-4d99-8ae8-2d19c3fd81e7' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/create-reactpy-app/create-reactpy-app
Deleting the contents of '/home/runner/work/create-reactpy-app/create-reactpy-app'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  The process '/usr/bin/git' failed with exit code 1
  Waiting 11 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
  Error: The process '/usr/bin/git' failed with exit code 1
```

I though that adding the `BRANCH` argument would resolve this, but I had no luck.
